name: Basic Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  go_test-latest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: 'stable'
        check-latest: true
    - run: go test -v ./...
  go_test-oldest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version-file: 'go.mod'
    - run: go test -v ./...
  ambitest-basic:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: 'stable'
        check-latest: true
    - run: go build -o $RUNNER_TEMP/ambitest -v ./internal/ambitest
    - run: $RUNNER_TEMP/ambitest
      env:
        AMBITEST_CH: ${{ secrets.AMBITEST_CH }}
        AMBITEST_USERKEY: ${{ secrets.AMBITEST_USERKEY }}
        AMBITEST_READKEY: ${{ secrets.AMBITEST_READKEY }}
        AMBITEST_WRITEKEY: ${{ secrets.AMBITEST_WRITEKEY }}
        AMBITEST_DEVKEY: ${{ secrets.AMBITEST_DEVKEY }}
